name: UI CI/CD build and deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - '.github/workflows/ui-build-and-deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'
      - '.github/workflows/ui-build-and-deploy.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
        
    - name: Install dependencies
      run: |
        cd client
        npm ci
        
    - name: Run linting
      run: |
        cd client
        npm run lint || echo "Linting not configured, skipping..."
        
    - name: Run tests
      run: |
        cd client
        npm run test -- --watch=false --browsers=ChromeHeadless --reporters=spec
        
    - name: Build application
      run: |
        cd client
        npm run build --configuration=production
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: client/dist/client/browser/
        retention-days: 1

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: client/dist/client/browser/
        
    - name: Deploy to Render
      id: deploy
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_UI_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        
    - name: Notify deployment
      run: |
        echo "✅ Frontend deployed successfully to Render!"
        echo "🔗 Frontend URL: https://weather-ai-assistant-ui.onrender.com/"
